---
title: "Testing Group Tabsets"
format: html
---
*excerpt from HLS_bulkdownload.qmd*

## Define Environment:

::: {.panel-tabset group="language"}

## R

```{r}
#| message: false

library(tidyverse)  # install.packages("tidyverse")
library(reticulate) # install.packages("reticulate")
library(httr)       # tidyverse, but not auto-loaded
library(jsonlite)   # tidyverse, but not auto-loaded
library(crul)       # install.packages("crul")


# install 
conda_install(envname = "r-reticulate", 
              packages = c("requests", "aiohttp"))

# import SciPy (will be automatically discovered in "r-reticulate")
aiohttp <- import("aiohttp")
requests <- import("requests")
```

## Python

```{python}
import requests
import math
import aiohttp 
import asyncio
import time
```
:::

## Define parameters needed for search:

1.  **URL**, for the LPCLOUD catalog

::: {.panel-tabset group="language"}

## R

```{r}
lpcloud_url <- "https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search"
```

## Python

```{python}
CMR_OPS= 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search'
url = f'{CMR_OPS}/{"granules"}'
```
:::
